alias cd="z"
alias ls="exa -l"
alias la="exa -la"
alias cat="bat"
alias grep="rg"
alias emacs="devour emacsclient -c -a emacs"
alias edemon="/usr/bin/emacs --daemon"
alias c="clear"
alias eshutdown="emerge --verbose --deep --newuse --update --with-bdeps=y @world | tee emerge-log.log && doas shutdown -h now"
